package tn.esprit.jmlessous.gestionuser.DAO.Entities;


public enum Address {
    ARIANA, BEJA, BENAROUS, BIZERTE, GABES,
    GAFSA, JENDOUBA, KAIROUAN, KASSERINE, KEBILI,
    KEF, MAHDIA, MANOUBA, MEDENINE, NABEUL, SFAX,
    SIDIBOUZID, SILIANA, SOUSSE, TATAOUINE, TOZEUR, TUNIS, ZAGHOUAN
}
